### ISSUE TITLE
Failed events - 400 Bad request

### ISSUE THREAD

**Issue by mlazari** [BranchMetrics/Segment-Branch-iOS#15]
When using Segment's [Event Delivery](https://segment.com/blog/new-data-visibility-features/) I see a lot of failed events for Branch destination with the description "400 Bad request". Most of them have one of these in "Response from Destination":

`"body": "{\n\t\"error\":\t{\n\t\t\"type\":\t\"not a valid option\"\n\t}\n}\n",`

`"body": "{\n\t\"error\":\t{\n\t\t\"event\":\t\"auto-tracked events are ignored\"\n\t}\n}\n",`

`"body": "{\n\t\"error\":\t\"dropping event without advertising_id or user_id\"\n}\n",`

For the first one "Request to Destination" contains this in body:
`"type": "screen",`

For the second one:
```
"event": "Application Opened",
"type": "track",
```

Any idea why these errors occur?

Also how this integration works? Does it send events from Segment server to Branch? I thought the events are only sent with Branch SDK from the mobile app:

https://segment.com/docs/guides/sources/why-do-some-mobile-destinations-require-packaging-their-sdks/
> We bundle certain SDKs, instead of just proxying your data to them through our servers...

**Comment by E-B-Smith** [comment]
Thanks for writing in -- sorry to hear your having issues.

Application events can be sent via the Segment SDK to Branch SDK integration or by Segment server to Branch Server integration.

If you integrate the Branch SDK via the Segment-Branch-iOS shim into your app, you don't need to use server-to-server integration since events tracked with the `[[SEGAnalytics sharedAnalytics] track:...]` will be passed to the Branch SDK and forwarded to our back end as well.

I haven't been able to reproduce your event tracking problem in my demo app yet but I'm looking into it.

Do you track events (calls to `[[SEGAnalytics sharedAnalytics] track:...]`) on multiple threads?

Also, can you turn on debug logging by setting  `BNCLogSetDisplayLevel(BNCLogLevelAll);` (obj-c) or `BNCLogSetDisplayLevel(.all)` (Swift) in your app delegate before initializing Segment and Branch.

You can either post the log here or email it to me at Branch.

**Comment by mlazari** [comment]
Thank you for the quick response.

> Application events can be sent via the Segment SDK to Branch SDK integration or by Segment server to Branch Server integration.

Can I choose between these 2? I think I need only Segment SDK to Branch SDK integration. I added Segment-Branch-iOS in the iOS app, so I think I don't need to use server-to-server integration. But the errors I see in Event Delivery are from server-to-server integration if I understand correctly. How to stop using server-to-server integration?

I don't call `track:` from multiple threads.

**Comment by E-B-Smith** [comment]
I would just use this Segment-Branch-iOS integration since it's more powerful.

Where are you seeing the errors?  In the device logs of the app, or on the segment dashboard?

If you're seeing them on the Segment dashboard then your seeing some sort of error with a server to server connection or a web hook.

You can disable that web hook in the Segment dashboard.  Check with Segment and their documentation about it.  I don't know enough about their dashboard to provide any quick tips about it.

Edit:
Please follow up here with what you find. I'd like to know what solved your problem too.

**Comment by E-B-Smith** [comment]
Please re-open this issue if this hasn't resolved your question.

**Comment by mlazari** [comment]
@E-B-Smith I see the errors in Segment dashboard, Event Delivery page ( see https://segment.com/blog/new-data-visibility-features/ ).
I just tried to send with Event Tester from Segment dashboard and I see the same errors when I send events. It only works (receiving a 202 Success response) when I select Track for event type.
![screen shot 2018-08-23 at 11 27 12 am](https://user-images.githubusercontent.com/4928274/44514517-09ed8b00-a6c9-11e8-88e7-d2ab5a336057.png)
![screen shot 2018-08-23 at 11 27 51 am](https://user-images.githubusercontent.com/4928274/44514519-0a862180-a6c9-11e8-8523-8a0b12068a75.png)

Not sure though if this is a Segment-Branch integration issue or a Segment issue.

I see the events in Branch Liveview page, I just don't understand why these errors appear in Segment dashboard. It looks like Segment server is trying to send "screen" events to Branch server (not sure why it does this, because iOS integration already sends these event from the mobile app), but does it in a way that Branch does not understand (Branch response basically says "screen" is not a valid value for "type" if I understand correctly).

**Comment by E-B-Smith** [comment]
You are seeing those errors because you have the Segment-to-Branch server-to-server interface turned on.  This connection is only meant for certain kinds of events and you have it configured to send all events.

You don't need this connection since you have the Branch SDK integrated in your app so just turn it off.

I am not very familiar with the Segment dashboard (I'm the SDK guy with Branch), but I believe if you go to the Segment dashboard, select 'Destinations' and disable Branch as a destination, you'll disable the server to server integration.  You'll still have Branch selected as a source though.

Segment can clarify this better than I can, I'm sure.

**Comment by mlazari** [comment]
I think I already tried without the Branch Metrics destination in Segment dashboard, but this makes Segment-Branch-iOS integration to be ignored. It's skipped here in Segment library (I was seeing "No settings for Branch Metrics. Skipping." in Xcode logs and the events were not appearing in Branch Liveview) :
https://github.com/segmentio/analytics-ios/blob/8eaf7cc0de903e20cfec91e68eb8c8ea9c6992ef/Analytics/Classes/Integrations/SEGIntegrationsManager.m#L361

Thank you very much for your help! I'll try to clarify with Segment if I don't find the solution.

**Comment by mlazari** [comment]
@E-B-Smith I found this comment today: https://github.com/segmentio/analytics-android/issues/406#issuecomment-276824795 and I think I understand now why some events are sent from Segment server. The build that includes this integration sends a dictionary like this:
```
integrations: {
  "Branch Metrics": false,
  // other client-side integrations
}
```
Segment looks to this dictionary and doesn't try to send the event from their server, because of the false value, which indicates that the event was already handled client-side.

But older versions of the app that don't have Branch Metric integration don't send that false value, thus Segment server tries to send the events from their server. But it looks like this doesn't work well. For example this client-side integration handles `screen` call like this:
```
- (void)screen:(SEGScreenPayload *)payload {
    if (payload.name.length) {
        NSMutableDictionary *state = [NSMutableDictionary dictionary];
        [state addEntriesFromDictionary:payload.properties];
        if (payload.category) {
            [state setObject:payload.category forKey:@"category"];
        }
        NSString *actionName = [NSString stringWithFormat:@"viewed_screen_%@", payload.name];
        [[Branch getInstance] userCompletedAction:actionName withState:state];
        SEGLog(@"[[Branch getInstance] userCompletedAction:%@ withState:%@]", actionName, payload.properties);
    }
}
```
Segment's server seems to not convert `screen` calls in a format that Branch understands and just passes `"type": "screen"` as is, thus this error:
`"body": "{\n\t\"error\":\t{\n\t\t\"type\":\t\"not a valid option\"\n\t}\n}\n",`

**Comment by danipralea** [comment]
@mlazari I also have this problem. Can you share what solution you reached, if you did? Segment support sent me back here.

**Comment by mlazari** [comment]
@danipralea We still didn't find a solution, just ignored those errors.
